name: firebase_chat
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  cached_network_image: ^3.3.0
  cloud_firestore: ^4.13.6
  cookie_jar: ^4.0.8
  crypto: ^3.0.3
  cupertino_icons: ^1.0.2
  device_info: null
  dio: ^5.4.0
  dio_cookie_manager: ^3.1.1
  dots_indicator: ^3.0.0
  firebase_auth: ^4.15.3
  firebase_core: ^2.24.2
  firebase_in_app_messaging: ^0.7.4+8
  firebase_messaging: ^14.7.9
  firebase_storage: ^11.5.6
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.1
  flutter_easyloading: ^3.0.5
  flutter_plugin_android_lifecycle: ^2.0.17
  flutter_screenutil: ^5.9.0
  flutter_spinkit: ^5.2.0
  fluttertoast: ^8.2.4
  get: ^4.6.6
  google_sign_in: ^6.2.1
  image_picker: ^1.0.5
  intl: ^0.19.0
  loading_animations: ^2.2.0
  location: ^5.0.3
  package_info: null
  packages_info: ^0.0.1-dev.1
  path_provider: ^2.1.1
  permission_handler: ^11.1.0
  photo_view: ^0.14.0
  pull_to_refresh: ^2.0.0
  sentry: ^7.14.0
  share: null
  shared_preferences: ^2.2.2
  uni_links: ^0.5.1
  webview_flutter: ^4.4.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
    - assets/icons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Avenir
      fonts:
        - asset: assets/fonts/Avenir-Book.ttf
          weight: 400
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
    - family: Iconfont
      fonts:
        - asset: assets/fonts/iconfont.ttf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
